import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MainContent from "../components/MainContent/MainContent";
import Sidebar from "../components/Sidebar";
import SidebarRight from "../components/SidebarRight/SidebarRight";
import Auth from "../layouts/MainLayout";

import { api } from "../utils/api";

const Home: NextPage = () => {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
                <div className="mx-auto">
                    <div className="flex flex-row justify-center">
                        <Sidebar />
                        <MainContent />
                        <SidebarRight />
                    </div>
                </div>
        </>
    );
};

export default Home;
